spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    password: postgres
    username: postgres
    host: postgres
    port: 5432
    database: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

debezium:
  slot:
    name: debezium_slot
  publication:
    name: debezium_publication
